model: "VGG_encrypted"
dataset: "CIFAR10"

fl:
  max_round: 80
  nb_clients: 10
  lr_clients: 1e-2

watermarking:
  max_ep_pretrain: 5
  max_ep_retrain: 3
  lr_pretrain: (1e-3, 1e-2) # ?
  lr_retrain: (1e-3, 1e-2) # ?